### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by shinobi8894** [naomis-novas/community#311] opened 2023-03-10 12:49 UTC
### Why do you want to join our organization?

As a Full Stack Designer || Developer, I wanna contribute to org

**Comment by shinobi8894** [comment] 2023-03-10 12:49
Thank you

**Comment by naomi-lgbt** [comment] 2023-03-10 17:37
Closing as duplicate of #310

**Closed by naomi-lgbt** 2023-03-10 17:37 UTC
Labels: ✉️ misc: invite to org
